theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
mouse = true
middle-click-paste = false
color-modes = true
text-width = 80
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
other-lines = "warning"

[editor.lsp]
enable = true
display-messages = true
display-progress-messages = true
display-inlay-hints = false

[editor.whitespace]
render = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-base-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
# Copy to both registers always
y = ["yank_to_clipboard", "yank"]

C-s = ":w" # (save file)

C-r = ":config-reload"
# Open yazi at current buffer's directory
C-y = ":open %sh{ zellij run -fc  -x 10%% -y 10%% --width 80%% --height 80%% -- sh -c \"yazi --chooser-file=/proc/$$/fd/1 -- %{buffer_name}; kill -s CONT $$\"; kill -s STOP $$ }"
# Open lazygit
C-m = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]

C-j = [
  "move_next_word_end",
  "select_mode",
  "insert_at_line_start",
  "move_line_down",
  "goto_next_paragraph",
  "normal_mode",
  "goto_prev_paragraph",
  "goto_next_paragraph",
  "trim_selections",
]

C-k = [
  "move_next_word_start",
  "select_mode",
  "insert_at_line_end",
  "move_line_up",
  "goto_prev_paragraph",
  "normal_mode",
  "goto_next_paragraph",
  "goto_prev_paragraph",
  "trim_selections",
]

[keys.normal.space]
Y = ":yank-diagnostic"

[keys.normal.";"]
f = "file_picker_in_current_buffer_directory"
F = "file_picker_in_current_directory"
e = "file_explorer_in_current_buffer_directory"
E = "file_explorer_in_current_working_directory"
s = "symbol_picker"
S = "workspace_symbol_picker"
g = "changed_file_picker"
b = "buffer_picker"
d = "diagnostics_picker"
D = "workspace_diagnostics_picker"
j = "jumplist_picker"
";" = "last_picker"


[keys.normal.z]
h = "goto_line_start"
l = "goto_line_end"

